config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  resources :users, only: [:create] # to override clearance route

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: "posts#index", as: :admin_root
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: "posts#index", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "pages#welcome"
  end

  resources :crews, path: '', only: [] do
    resources :posts, only: [:index, :show]

    resources :users, path: '', only: [:edit, :update] do
      resources :posts, except: :show do
        member do
          post :go_live
          post :archive
          delete :remove_header_images
        end
        resources :comments, only: [:create, :destroy]
      end
      resources :crew_memberships, only: :destroy
    end
  end

  resources :images, only: [] do
    collection do
      post :search_unsplash
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
  alias_method :commented_by, :user

  before_validation :add_default_text

  delegate :crew_id, to: :post
  delegate :crew, to: :post

  private

  def add_default_text
    return unless self.text.blank? && Rails.env.development?

    self.text = Api::HipsterIpsum.default_text
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: :create
  before_action :set_comment, only: :destroy

  def create
    @comment = @post.comments.new(comment_params.merge({ user_id: current_user.id }))
    @comment.save! ? flash[:success] = 'You have commented!' : flash[:error] = 'Problem creating comment, please try again.'

    redirect_to crew_post_path(@post.crew, @post)
  end

  def destroy
    authorize @comment

    @comment.destroy
  end

  private

  def set_post
    @post = Post.find_by_id(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_comment
    @comment = current_user.comments.find_by(id: params[:id])
  end
end

app/views/comments/_comment.html.erb
<div class="card" id="<%= dom_id comment %>">
  <div class="card-content">

    <nav class="level is-mobile comment-header">
      <div class="level-left">
        <h5 class="title is-size-5">
          <%= comment.commented_by.name.familiar %>
        </h5>
      </div>
      <div class="level-right">
        <% if policy(comment).destroy? %>
          <%= link_to crew_user_post_comment_path(@crew, current_user, @post, comment),
                      data: { behavior: 'delete-comment' }, class: 'button is-text' do %>
            <i class="fas fa-trash"></i>
            Delete
          <% end %>
        <% end %>
      </div>
    </nav>

    <nav class="level is-mobile comment-time">
      <div class="level-left">
        <%= distance_of_time_in_words(Time.zone.now, comment.created_at) %> ago
      </div>
      <div class="level-right"></div>
    </nav>

    <div class="content"><%= comment.text %></div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@crew, current_user, @post, @post.comments.new],
              local: true, id: 'create-comment-form' do |f| %>
  <div class="field">
    <div class="control">
      <%= f.text_area :text,
                      placeholder: 'Write your comment here...',
                      required: true, class: 'textarea' %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit 'Save', class: 'button is-primary' %>
    </div>
  </div>
<% end %>