config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  resources :users, only: [:create] # to override clearance route

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: "posts#index", as: :admin_root
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: "posts#index", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "pages#welcome"
  end

  resources :crews, path: '', only: [] do
    resources :posts, only: [:index, :show]

    resources :users, path: '', only: [:edit, :update] do
      resources :posts, except: :show do
        member do
          post :go_live
          post :archive
          delete :remove_header_images
        end
        resources :comments, only: [:create, :destroy]
      end
      resources :crew_memberships, only: :destroy
    end
  end

  resources :images, only: [] do
    collection do
      post :search_unsplash
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_person_name

  has_many :crew_memberships
  has_many :crews, through: :crew_memberships
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :first_name, :last_name, presence: true

  def to_param
    (first_name.first + last_name).downcase
  end

  def has_many_crews?
    crews.size > 1
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :get_crew_by_join_code, only: :create
  before_action :redirect_signed_in_users, only: :create
  skip_before_action :require_login, raise: false, only: :create
  before_action :set_current_crew, except: :create
  before_action :set_crew_membership, only: :edit

  def create
    @user = User.new(user_params).tap { |u| u.crews << @crew }

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:success] = "Updates were successful!"
      redirect_to edit_crew_user_path(@crew, current_user)
    else
      render :edit
    end
  end

  private

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def get_crew_by_join_code
    join_code = params[:user][:crew_join_code]
    unless (@crew = Crew.find_by(join_code: join_code))
      flash.now[:error] = "Unable to find a crew with that code! 😭 Please verify \"#{join_code}\" is correct and try again."
      render template: "users/new"
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end
end

app/helpers/user_helper.rb
module UserHelper
  def ability_icons(membership:)
    icons = ['<i class="fas fa-eye"></i>']
    icons << '<i class="fas fa-pen-nib"></i>' if membership.poster?
    icons << '<i class="fas fa-shield-alt"></i>' if membership.crew_admin?

    sanitize(icons.join(' '))
  end
end

app/views/users/_edit_form.html.erb
<%= form_with model: [@crew, current_user],
              method: :patch, local: true do |f| %>
  <div class="field">
    <%= f.label :first_name, class: 'label' %>
    <div class="control has-icons-left">
      <%= f.text_field :first_name, class: 'input',
                       placeholder: 'first name', required: true %>
      <span class="icon is-small is-left">
        <i class="fas fa-user"></i>
      </span>
    </div>
  </div>
  <div class="field">
    <%= f.label :last_name, class: 'label' %>
    <div class="control has-icons-left">
      <%= f.text_field :last_name, class: 'input',
                       placeholder: 'last name', required: true %>
      <span class="icon is-small is-left">
        <i class="fas fa-user"></i>
      </span>
    </div>
  </div>
  <div class="field">
    <%= f.label :email, class: 'label' %>
    <div class="control has-icons-left">
      <%= f.text_field :email, type: 'email', class: 'input',
                       placeholder: 'email', required: true %>
      <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
      </span>
    </div>
  </div>
  <div class="field">
    <%= f.label :password, 'Change password', class: 'label' %>
    <div class="control has-icons-left">
      <%= f.password_field :password, type: 'password', class: 'input',
                           placeholder: 'password', required: true %>
      <span class="icon is-small is-left">
        <i class="fas fa-lock"></i>
      </span>
    </div>
  </div>
  <div class="submit-field">
    <%= f.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
  <div class="text-field field">
    <label class="label">Crew Code</label>
    <div class="control has-icons-left">
      <%= form.text_field :crew_join_code, value: params[:crew_join_code],
                          class: 'input is-large', placeholder: 'crew code', required: true %>
      <span class="icon is-small is-left">
        <i class="fas fa-user-secret"></i>
      </span>
    </div>
  </div>

  <hr>

  <div class="text-field field">
    <nav class="level">
      <div class="level-item">
      <div class="control has-icons-left">
        <%= form.text_field :first_name, class: 'input',
                            placeholder: 'first name', required: true %>
        <span class="icon is-small is-left">
          <i class="fas fa-user"></i>
        </span>
      </div>
      </div>
      <div class="level-item">
        <div class="control has-icons-left">
          <%= form.text_field :last_name, class: 'input',
                              placeholder: 'last name', required: true %>
          <span class="icon is-small is-left">
        <i class="fas fa-user"></i>
      </span>
        </div>
      </div>
    </nav>
  </div>

  <div class="text-field field">
    <div class="control has-icons-left">
      <%= form.text_field :email, type: 'email', class: 'input',
                          placeholder: 'email', required: true %>
      <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
      </span>
    </div>
  </div>

  <div class="password-field field">
    <div class="control has-icons-left">
      <%= form.password_field :password, type: 'password', class: 'input',
                              placeholder: 'password', required: true %>
      <span class="icon is-small is-left">
        <i class="fas fa-lock"></i>
      </span>
    </div>
  </div>

  <div class="submit-field">
    <%= form.submit class: 'button is-primary' %>
  </div>

  <div class="other-links has-text-centered">
    <%= link_to 'Sign In', sign_in_path %>
  </div>
<% end %>

app/views/users/_memberships_table.html.erb
<h3 class="title is-size-3">Memberships</h3>
<table class="table is-hoverable is-fullwidth">
  <thead>
  <tr>
    <th>Name</th>
    <th>Abilities</th>
    <th class="has-text-centered">Remove?</th>
  </tr>
  </thead>
  <tbody>
  <% current_user.crew_memberships.each do |membership| %>
    <tr>
      <td><%= membership.crew.name %></td>
      <td><%= ability_icons(membership: membership) %></td>
      <td class="has-text-centered">
        <%= link_to crew_user_crew_membership_path(@crew, current_user, membership),
                    data: { behavior: 'delete-crew-membership' }, class: 'button is-small is-danger is-light' do %>
          <i class="fas fa-times"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/_user_stats.html.erb
<h3 class="title is-size-3">Stats</h3>
<div class="block">
  <strong>Joined Date:</strong> <%= format_datetime(current_user.created_at) %>
</div>
<% if current_user.posts.present? %>
  <div class="block">
    <strong>Posts:</strong> <%= current_user.posts.size %>
  </div>
<% end %>
<div class="block">
  <strong>Comments:</strong> <%= current_user.comments.size %>
</div>

app/views/users/edit.html.erb
<div class="box" id="user-edit">
  <h2 class="title is-size-2">Account Details</h2>
  <hr>
  <div class="columns is-variable is-5">
    <div class="column is-one-third">
      <%= render 'edit_form' %>
    </div>
    <div class="column is-one-third">
      <%= render 'memberships_table' %>
    </div>
    <div class="column is-one-third">
      <%= render 'user_stats' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-in columns is-centered is-mobile">
  <div class="box column is-10-mobile is-8-tablet is-8-desktop is-6-widescreen">
    <h2 class="title is-4"><%= t(".title") %></h2>

    <%= render partial: '/users/form' %>
  </div>
</div>