config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  resources :users, only: [:create] # to override clearance route

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: "posts#index", as: :admin_root
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: "posts#index", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "pages#welcome"
  end

  resources :crews, path: '', only: [] do
    resources :posts, only: [:index, :show]

    resources :users, path: '', only: [:edit, :update] do
      resources :posts, except: :show do
        member do
          post :go_live
          post :archive
          delete :remove_header_images
        end
        resources :comments, only: [:create, :destroy]
      end
      resources :crew_memberships, only: :destroy
    end
  end

  resources :images, only: [] do
    collection do
      post :search_unsplash
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :crew
  has_one :background_image, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :header_images

  accepts_nested_attributes_for :background_image,
                                allow_destroy: true,
                                reject_if: proc { |attributes| attributes['image_url'].blank? }

  has_rich_text :body
  validates :body, presence: true
  alias_method :posted_by, :user

  before_validation :add_default_text

  scope :lifo, -> { order(updated_at: :desc) }
  scope :in_progress, -> { where(live: false, archived: false) }
  scope :live, -> { where(live: true, archived: false) }
  scope :archived, -> { where(archived: true) }
  scope :current_users_posts, -> (user_id) { where(user_id: user_id) }
  scope :other_users_posts, -> (user_id) { where.not(user_id: user_id) }
  
  private

  def add_default_text
    return unless self.body.blank? && Rails.env.development?

    self.body = Api::HipsterIpsum.default_text
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_current_crew
  before_action :set_crew_membership
  before_action :set_post, except: [:index, :new, :create, :show]
  before_action :set_live_post, only: :show

  def index
    @posts_facade = PostsFacade.new(user: current_user, crew: @crew)
  end

  def new
    @post = @crew.posts.new

    authorize @post
  end

  def create
    @post = @crew.posts.new(post_params.merge({ user_id: current_user.id }))

    authorize @post
    unsplash_download_event

    if @post.save
      flash[:success] = "\"#{@post.title}\" has been created!"
      redirect_to crew_user_posts_path(@crew, current_user)
    else
      render :new
    end
  end

  def show
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    unsplash_download_event
    if @post.update(post_params)
      flash[:success] = "\"#{@post.title}\" has been updated!"
      redirect_to crew_user_posts_path(@crew, current_user)
    else
      render :edit
    end
  end

  def destroy
    authorize @post

    @post.destroy
  end

  def go_live
    authorize @post

    @post.update(live: true)
    NotifyCrewOfLivePostJob.perform_later(post_id: @post.id, crew_id: @crew.id)
  end

  def archive
    authorize @post

    @post.update(archived: true)
  end

  def remove_header_images
    authorize @post

    @post.header_images.purge
  end

  private

  def post_params
    params.require(:post).permit(:title, :body,
                                 header_images: [],
                                 background_image_attributes: [:id, :image_url,
                                                               :attribution_name,
                                                               :attribution_url])
  end

  def set_post
    unless (@post = @crew.posts.includes(:comments).find_by_id(params[:id]))
      flash[:error] = 'Unable to find that post, please verify and try again.'
      redirect_to crew_user_posts_path(@crew, current_user)
    end
  end

  def set_live_post
    # to allow posters to view before it goes live
    @post = Post.find_by_id(params[:id])
    if @post
      return if @post.posted_by == current_user
      unless @post.live?
        flash[:error] = 'Unable to find that post, please verify and try again.'
        redirect_to crew_user_posts_path(@crew, current_user)
      end
    else
      flash[:error] = 'Unable to find that post, please verify and try again.'
      redirect_to crew_user_posts_path(@crew, current_user)
    end
  end

  def unsplash_download_event
    UnsplashDownloadEventJob.perform_later(params[:unsplash_id]) if params[:unsplash_id]
  end
end

app/helpers/post_helper.rb
module PostHelper
  def index_title_text(is_poster:, crew_name:)
    is_poster ? 'Your Posts' : "#{crew_name} Posts"
  end

  def byline_text(name:, updated_at:)
    "by #{name} at #{format_datetime(updated_at)}"
  end

  def comment_heading_text(num_of_comments:)
    base_text = 'Comments'
    num_of_comments.zero? ? base_text : base_text + " (#{num_of_comments})"
  end

  def header_images_css_column_class(num_images)
    num_images == 1 ? 'is-full' : 'is-full-mobile is-half-tablet is-half-desktop'
  end
end

app/views/posts/_comment_section.html.erb
<% if @post.comments.present? %>
  <nav class="panel">
    <p class="panel-heading">
      <%= comment_heading_text(num_of_comments: @post.comments.size) %>
    </p>
    <div id="post-comments">
      <% @post.comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
    </div>
  </nav>
<% end %>

<button class="button is-text" id="add-comment-button">
  <i class="fas fa-plus"></i>
  Comment
</button>

<%= render 'comments/form' %>

app/views/posts/_form.html.erb
<%= form_with model: [@crew, current_user, @post], local: true do |f| %>
  <div class="field">
    <div class="control">
      <%= f.text_field :title,
                       placeholder: 'Title', required: true,
                       maxlength: 250, class: 'input is-large' %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <div class="file has-name">
        <label class="file-label">
          <input class="file-input" type="file" name="image">
          <span class="file-cta">
            <span class="file-icon">
            <i class="fas fa-upload"></i>
            </span>
            <%= f.file_field :header_images, multiple: true %>
          </span>
        </label>
      </div>
    </div>
    <% if @post.header_images.attached? %>
      <section class="section" id="header-images-container" >
        <div class="columns is-multiline">
          <% @post.header_images.each do |h_image| %>
            <div class="column <%= header_images_css_column_class(@post.header_images.size) %>">
              <figure class="image"><%= image_tag(h_image) %></figure>
            </div>
          <% end %>
        </div>
        <nav class="level">
          <div class="level-left">
            <%= link_to 'Remove Images', remove_header_images_crew_user_post_path(@crew, current_user, @post),
                        data: { behavior: 'remove-header-images' }, class: 'button is-text' %>
          </div>
        </nav>
      </section>
    <% end %>
  </div>
  <div class="field">
    <div class="control">
      <%= f.rich_text_area :body,
                           placeholder: 'Write your thoughts here...' %>
    </div>
  </div>
  <%= f.fields_for :background_image,
                   (@post.build_background_image unless @post.background_image) do |ff| %>
    <%= hidden_field_tag :unsplash_id %>
    <%= ff.hidden_field :image_url %>
    <%= ff.hidden_field :attribution_name %>
    <%= ff.hidden_field :attribution_url %>
  <% end %>

  <nav class="level">
    <div class="level-left">
      <%= f.submit 'Save', class: 'button is-primary' %>
      <%= link_to 'Cancel', crew_user_posts_path(@crew, current_user),
                  class: 'button is-text' %>
    </div>
    <div class="level-right">
      <% if @post.persisted? %>
        <% if policy(@post).archive? && !@post.archived? %>
          <%= link_to archive_crew_user_post_path(@crew, current_user, @post),
                      data: { behavior: 'archive' }, class: 'button is-text' do %>
            <i class="fas fa-archive"></i>
            Archive
          <% end %>
        <% end %>
      <% end %>
    </div>
  </nav>
<% end %>

app/views/posts/_posts_section.html.erb
<div class="columns is-multiline posts-container">
  <% posts.each do |post| %>
    <div class="column is-full-mobile is-half-tablet is-one-third-desktop">
      <div class="box">
        <h4 class="post-title is-size-4">
          <%= link_to post.title.truncate(50), crew_post_path(@crew, post) %>
        </h4>
        <p class="byline"><%= byline_text(name: post.posted_by.name.familiar, updated_at: post.updated_at) %></p>

        <%= sanitize("<hr>") if @crew_membership&.poster? %>

        <% if policy(post).go_live? && !(post.live? || post.archived?) %>
          <nav class="level is-mobile">
            <div class="level-left"></div>
            <div class="level-right">
              <%= link_to 'Go Live!', go_live_crew_user_post_path(@crew, current_user, post),
                          data: { behavior: 'go-live' }, class: 'button is-primary' %>
            </div>
          </nav>
        <% end %>
        <nav class="level is-mobile">
          <div class="level-left"></div>
          <div class="level-right">
            <% if policy(post).edit? %>
              <%= link_to edit_crew_user_post_path(@crew, current_user, post),
                          class: 'button is-text' do %>
                <i class="fas fa-edit"></i>
                Edit
              <% end %>
            <% end %>

            <% if policy(post).archive? && !post.archived? %>
              <%= link_to archive_crew_user_post_path(@crew, current_user, post),
                          data: { behavior: 'archive' }, class: 'button is-text' do %>
                <i class="fas fa-archive"></i>
                Archive
              <% end %>
            <% end %>

            <% if policy(post).destroy? %>
              <%= link_to crew_user_post_path(@crew, current_user, post),
                          data: { behavior: 'delete' }, class: 'button is-text' do %>
                <i class="fas fa-trash"></i>
                Delete
              <% end %>
            <% end %>
          </div>
        </nav>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_unsplash_search_form.html.erb
<%= form_with url: search_unsplash_images_path do |f| %>
  <div class="field has-addons">
    <div class="control">
      <%= f.text_field :search_term,
                       placeholder: 'Background image',
                       class: 'input' %>
      <%= f.hidden_field :orientation, value: 'landscape' %>
    </div>
    <div class="control">
      <%= f.submit 'Search', class: 'button is-link' %>
    </div>
  </div>
<% end %>

<div id="unsplash-results"><div class="columns is-multiline"></div></div>

app/views/posts/edit.html.erb
<div class="box" id="user-posts-edit">
  <%= render 'layouts/error_messages', obj: @post %>
  <h2 class="is-size-2">Edit Post</h2>

  <%= render 'unsplash_search_form' %>

  <hr>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div id="user-posts-index">
  <h2 class="is-size-2" id="index-heading">
    <%= index_title_text(is_poster: @crew_membership&.poster?,
                         crew_name: @crew.name) %>
  </h2>

  <% if @crew_membership&.poster? && @posts_facade.live_posts.present? %>
    <h4 class="is-size-4 index-subheading">Live</h4>
  <% end %>
  <%= render 'posts_section', posts: @posts_facade.live_posts %>

  <% if @posts_facade.in_progress_posts.present? %>
    <hr>
    <h4 class="is-size-4 index-subheading">In-Progress</h4>
    <%= render 'posts_section', posts: @posts_facade.in_progress_posts %>
  <% end %>

  <% if @crew_membership&.poster? && @posts_facade.other_posts.present? %>
    <hr>
    <h4 class="is-size-4 index-subheading">Other Users Posts</h4>
    <%= render 'posts_section', posts: @posts_facade.other_posts %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="box" id="user-posts-new">
  <%= render 'layouts/error_messages', obj: @post %>
  <h2 class="is-size-2">New Post</h2>

  <%= render 'unsplash_search_form' %>
  <hr>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="box" id="user-posts-show">
  <h1 class="title is-size-1 post-title"><%= @post.title %></h1>
  <h5 class="subtitle is-size-5" id="byline">
    <%= byline_text(name: @post.posted_by.name.familiar, updated_at: @post.updated_at) %>
  </h5>
  <hr>
  <% if @post.header_images.attached? %>
    <div id="header-images-container" class="columns is-multiline">
      <% @post.header_images.each do |h_image| %>
        <div class="column <%= header_images_css_column_class(@post.header_images.size) %>">
          <figure class="image"><%= image_tag(h_image) %></figure>
        </div>
      <% end %>
    </div>
  <% end %>
  <p><%= @post.body %></p>
  <hr>
  <%= render 'comment_section' %>
</div>