config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  resources :users, only: [:create] # to override clearance route

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: "posts#index", as: :admin_root
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: "posts#index", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "pages#welcome"
  end

  resources :crews, path: '', only: [] do
    resources :posts, only: [:index, :show]

    resources :users, path: '', only: [:edit, :update] do
      resources :posts, except: :show do
        member do
          post :go_live
          post :archive
          delete :remove_header_images
        end
        resources :comments, only: [:create, :destroy]
      end
      resources :crew_memberships, only: :destroy
    end
  end

  resources :images, only: [] do
    collection do
      post :search_unsplash
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if obj.try(:errors) && obj.errors.any? %>
  <div class="<%= flash_class('error') %>">
    <%= obj.errors.full_messages.join(', ') %>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>AdventBeer.com</strong> by <a target="_blank" href="https://www.amyers.io">amyers.io</a>
      <%= footer_credit_links(post: @post) %>
    </p>
  </div>
</footer>

app/views/layouts/_image_modal.html.erb
<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-content" id="image-modal-content">
    <p class="image">
      <img src="" alt="">
    </p>
  </div>
  <button class="modal-close is-large" aria-label="close"></button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-fixed-top" id="advent-beer-navbar"
     role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item is-size-3" do %>
        <span id="navbar-logo">AdventBeer</span>
      <% end %>
      <a role="button" class="navbar-burger burger">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-menu">
      <div class="navbar-end">
        <% if signed_in? %>
          <div class="navbar-item">
            <%= link_to crew_user_posts_path(@crew, current_user), class: 'button is-light' do %>
              <i class="fas fa-home"></i>
              Home
            <% end %>
          </div>
          <% if @crew_membership&.poster? %>
            <div class="navbar-item">
              <%= link_to new_crew_user_post_path(@crew, current_user), class: 'button is-primary' do %>
                <i class="fas fa-plus"></i>
                <i class="fas fa-pen-nib"></i>
                New
              <% end %>
            </div>
          <% end %>
          <% if current_user.has_many_crews? %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <%= @crew.name %>
                <i class="fas fa-angle-down"></i>
              </a>
              <div class="navbar-dropdown">
                <% current_user.crews.each do |crew| %>
                  <%= link_to crew.name,
                              crew_posts_path(crew),
                              class: 'navbar-item' %>
                <% end %>
              </div>
            </div>
          <% end %>
          <div class="navbar-item is-hidden-touch"></div>
          <div class="navbar-item">
            <%= link_to edit_crew_user_path(@crew, current_user), class: 'button is-link' do %>
              <i class="fas fa-user"></i>
              Profile
            <% end %>
          </div>
          <div class="navbar-item">
            <%= button_to sign_out_path, method: :delete, class: 'button is-link' do %>
              <i class="fas fa-sign-out-alt"></i>
              Sign Out
            <% end %>
          </div>
        <% else %>
          <div class="navbar-item">
            <%= link_to 'Join', sign_up_path, class: 'button is-primary' %>
          </div>
          <div class="navbar-item">
            <%= link_to 'Sign In', sign_in_path, class: 'button is-light' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AdventBeer.com</title>
    <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'stylesheets', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
  </head>

  <body class="has-navbar-fixed-top" style="<%= background_image_css(post: @post) %>">
    <%= render 'layouts/navbar' %>
    <div id="main-container" class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
      <%= render 'layouts/image_modal' %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>